apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crd-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crd-test
    spec:
      containers:
        - name: crd-test
          image: github.com/houshengbo/crd-example/cmd
          imagePullPolicy: IfNotPresent
