apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stars.example.crd.com
spec:
  group: example.crd.com
  scope: Namespaced
  names:
    kind: Star
    listKind: StarList
    plural: stars
    singular: star
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["type","location"]
          properties:
            type:
              type: "string"
              minimum: 1
            location:
              type: "string"
              minimum: 1
  versions:
    - name: v1alpha1
      served: true
      storage: true
